package sv.com.p4.model;
// Generated 05-18-2018 04:53:51 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo  implements java.io.Serializable {


     private Long idVehiculo;
     private String marca;
     private String modelo;
     private String color;
     private Date fechaCompra;

    public Vehiculo() {
    }

    public Vehiculo(String marca, String modelo, String color, Date fechaCompra) {
       this.marca = marca;
       this.modelo = modelo;
       this.color = color;
       this.fechaCompra = fechaCompra;
    }
   
    public Long getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(Long idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }




}


